import { weaponType } from './../../autogenerated/entities/WeaponType';
import { TestBed, inject } from '@angular/core/testing';

import { FormDataHelper } from './FormDataHelper';
import { Ganger } from '../../autogenerated/entities/Ganger';
import { Weapon } from '../../autogenerated/entities/Weapon';
import { gangerType } from 'autogenerated/entities/GangerType';
import { GangerWeapon } from 'autogenerated/entities/GangerWeapon';

describe('FormDataHelper', () => {
  it('should run unit tests', () => {
    expect(true).toBeTruthy();
  });
});
