language: csharp
solution: Hivemind.sln
dotnet: 2.0.0
env: 
  - NODE_VERSION="8.9"
before_install:
  - nvm install $NODE_VERSION
install:
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
  - dotnet restore ./Hivemind.Core/Hivemind.Core.csproj
  - dotnet restore ./Hivemind.Core.Tests/Hivemind.Core.Tests.csproj
  - msbuild /p:Configuration=Release ./Hivemind.Api.Tests/Hivemind.Api.Tests.csproj
  - mkdir ./testresults ./nuget
script: ./build/build.sh