language: csharp
solution: Hivemind.sln
dotnet: 2.1
env: 
  - NODE_VERSION="8.9"
before_install:
  - chmod +x ./build.sh
  - nvm install $NODE_VERSION
install:
  - dotnet restore ./Hivemind.Core/Hivemind.Core.csproj
  - dotnet restore ./Hivemind.Core.Tests/Hivemind.Core.Tests.csproj
  - mkdir ./testresults ./nuget
script: ./build.sh