import { GangTerritory } from './../../autogenerated/entities/GangTerritory';
import { Territory } from './../../autogenerated/entities/Territory';
import { Store } from 'redux';
import { IAppState } from '../redux/IAppState';
import { Ganger } from './../../autogenerated/entities/Ganger';
import { NgRedux } from '@angular-redux/store';
import { Gang } from './../../autogenerated/entities/Gang';
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'gang',
  templateUrl: './gang.component.html',
  styleUrls: ['./gang.component.css']
})
export class GangComponent {

  @Input() public gang: Gang;
  public gangers: Ganger[];
  public territories: GangTerritory[];
  public activeTab = 1;
  public isGameInProgress: boolean;

  constructor() {
    this.gangers = [
      new Ganger({
        move: 4,
        weaponSkill: 4,
        ballisticSkill: 4,
        toughness: 3,
        strength: 3,
        wounds: 1,
        initiative: 4,
        attack: 1,
        leadership: 8,
        cost: 120,
        experience: 60,
        title: 'GANG_CHAMPION',
        active: true,
        gangerType: 'LEADER',
        name: 'Eddu',
        rightHandFingers: 5,
        leftHandFingers: 5
      }),
      new Ganger({
        move: 4,
        weaponSkill: 3,
        ballisticSkill: 3,
        toughness: 3,
        strength: 3,
        wounds: 1,
        initiative: 3,
        attack: 1,
        leadership: 7,
        cost: 60,
        experience: 60,
        title: 'GANG_CHAMPION',
        active: true,
        gangerType: 'HEAVY',
        name: 'Bazooka Josef',
        rightHandFingers: 5,
        leftHandFingers: 4
      }),
      new Ganger({
        move: 4,
        weaponSkill: 3,
        ballisticSkill: 3,
        toughness: 3,
        strength: 3,
        wounds: 1,
        initiative: 3,
        attack: 1,
        leadership: 7,
        cost: 50,
        experience: 20,
        title: 'NEW_GANGER',
        active: true,
        gangerType: 'GANGER',
        name: 'Sprack',
        rightHandFingers: 5,
        leftHandFingers: 5
      }),
      new Ganger({
        move: 4,
        weaponSkill: 3,
        ballisticSkill: 3,
        toughness: 3,
        strength: 3,
        wounds: 1,
        initiative: 3,
        attack: 1,
        leadership: 7,
        cost: 50,
        experience: 20,
        title: 'NEW_GANGER',
        active: true,
        gangerType: 'GANGER',
        name: 'Fangle',
        rightHandFingers: 5,
        leftHandFingers: 5
      }),
      new Ganger({
        move: 4,
        weaponSkill: 2,
        ballisticSkill: 2,
        toughness: 3,
        strength: 3,
        wounds: 1,
        initiative: 3,
        attack: 1,
        leadership: 6,
        cost: 25,
        experience: 20,
        title: 'GREEN_JUVE',
        active: true,
        gangerType: 'JUVE',
        name: 'Bort',
        rightHandFingers: 5,
        leftHandFingers: 5
      })
    ];

    this.gang = new Gang({
      gangId: 'abcdef',
      name: 'Righteous Raiders',
      credits: 1000,
      gangHouse: 'VAN_SAAR',
      gangers: this.gangers,
      gangRating: 1012,
      territories: [
        new GangTerritory({
          gangId: 'abcdef',
          gangTerritoryId: 'ghijkl',
          territory: new Territory({
            territoryId: 1,
            name: 'Chem Pit',
            description: 'Chem pit description',
            income: '2D6'
          })
        })
      ]
    });

    this.territories = this.gang.territories;

    console.log(this.gang);
  }

  public startGame() {
    this.isGameInProgress = true;
  }

  public cancelGame() {
    this.isGameInProgress = false;
  }
}
