CREATE TABLE [dbo].[Gangers] (
    [gangerId]           NVARCHAR (100) NOT NULL,
    [gangId]             NVARCHAR (100) NOT NULL,
    [name]               NVARCHAR (100) NOT NULL,
    [type]               INT            NOT NULL,
    [move]               INT            NOT NULL,
    [weaponSkill]        INT            NOT NULL,
    [ballisticSkill]     INT            NOT NULL,
    [strength]           INT            NOT NULL,
    [toughness]          INT            NOT NULL,
    [wounds]             INT            NOT NULL,
    [initiative]         INT            NOT NULL,
    [attack]             INT            NOT NULL,
    [leadership]         INT            NOT NULL,
    [experience]         INT            NOT NULL,
    [active]             TINYINT        NOT NULL,
    [isOneEyed]          TINYINT        DEFAULT ((0)) NOT NULL,
    [isDeafened]         TINYINT        DEFAULT ((0)) NOT NULL,
    [isOneHanded]        TINYINT        DEFAULT ((0)) NOT NULL,
    [rightHandFingers]   INT            DEFAULT ((5)) NOT NULL,
    [leftHandFingers]    INT            DEFAULT ((5)) NOT NULL,
    [hasHorribleScars]   TINYINT        NOT NULL,
    [hasImpressiveScars] TINYINT        DEFAULT ((0)) NOT NULL,
    [hasHeadWound]       TINYINT        DEFAULT ((0)) NOT NULL,
    [hasOldBattleWound]  TINYINT        DEFAULT ((0)) NOT NULL,
    [IsCaptured]         TINYINT        DEFAULT ((0)) NOT NULL,
    [hasBitterEnmity]    TINYINT        DEFAULT ((0)) NOT NULL,
    [hasSporeSickness]   TINYINT        DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Gangers] PRIMARY KEY CLUSTERED ([gangerId] ASC),
    CONSTRAINT [FK_Gangs_Gangers] FOREIGN KEY ([gangId]) REFERENCES [dbo].[Gangs] ([gangId])
);

