/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

export enum gameType {
    GangFight = 1,
    Scavengers,
    HitAndRun,
    Ambush,
    TheRaid,
    RescueMission,
    Shootout,
}