/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Ganger } from './Ganger';
import { Injury } from './Injury';
import { HttpParams } from '@angular/common/http';

export class GangerInjuryReport {
    public theGanger: Ganger;
    public injuries: Injury[];

    public constructor(partial: Partial<GangerInjuryReport>) {
        if (partial.theGanger) {
            this.theGanger = partial.theGanger;
        }
        if (partial.injuries) {
            this.injuries = partial.injuries;
        }
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //    .set('theGanger', this.theGanger !== undefined ? this.theGanger.toString() : '')
        //    .set('injuries', this.injuries !== undefined ? this.injuries.toString() : '')
        //      ;

        let params = new HttpParams();
        let properties = [];
        if (this.theGanger) {
            properties.push('theGanger');
        }
        if (this.injuries) {
            properties.push('injuries');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}