/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Territory } from './Territory';
import { HttpParams } from '@angular/common/http';

export class GangTerritory {
    public gangTerritoryId: string;
    public gangId: string;
    public territory: Territory;

    public constructor(partial: Partial<GangTerritory>) {
        if (partial.gangTerritoryId) {
            this.gangTerritoryId = partial.gangTerritoryId;
        }
        if (partial.gangId) {
            this.gangId = partial.gangId;
        }
        if (partial.territory) {
            this.territory = partial.territory;
        }
    }

    public toHttpParams(): HttpParams {
        let params = new HttpParams();
        let properties = [];
        if (this.gangTerritoryId) {
            properties.push('gangTerritoryId');
        }
        if (this.gangId) {
            properties.push('gangId');
        }
        if (this.territory) {
            properties.push('territory');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}