/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Weapon } from './Weapon';
import { HttpParams } from '@angular/common/http';

export class GangerWeapon {
    public gangerWeaponId: string;
    public gangerId: string;
    public weapon: Weapon;

    public constructor(partial: Partial<GangerWeapon>) {
        if (partial.gangerWeaponId) {
            this.gangerWeaponId = partial.gangerWeaponId;
        }
        if (partial.gangerId) {
            this.gangerId = partial.gangerId;
        }
        if (partial.weapon) {
            this.weapon = partial.weapon;
        }
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //    .set('gangerWeaponId', this.gangerWeaponId !== undefined ? this.gangerWeaponId.toString() : '')
        //    .set('gangerId', this.gangerId !== undefined ? this.gangerId.toString() : '')
        //    .set('weapon', this.weapon !== undefined ? this.weapon.toString() : '')
        //      ;

        let params = new HttpParams();
        let properties = [];
        if (this.gangerWeaponId) {
            properties.push('gangerWeaponId');
        }
        if (this.gangerId) {
            properties.push('gangerId');
        }
        if (this.weapon) {
            properties.push('weapon');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}