/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Weapon } from './Weapon';
import { HttpParams } from '@angular/common/http';

export class GangWeapon {
    public gangWeaponId: string;
    public gangId: string;
    public weapon: Weapon;

    public constructor(partial: Partial<GangWeapon>) {
        if (partial.gangWeaponId) {
            this.gangWeaponId = partial.gangWeaponId;
        }
        if (partial.gangId) {
            this.gangId = partial.gangId;
        }
        if (partial.weapon) {
            this.weapon = partial.weapon;
        }
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //    .set('gangWeaponId', this.gangWeaponId !== undefined ? this.gangWeaponId.toString() : '')
        //    .set('gangId', this.gangId !== undefined ? this.gangId.toString() : '')
        //    .set('weapon', this.weapon !== undefined ? this.weapon.toString() : '')
        //      ;

        let params = new HttpParams();
        let properties = [];
        if (this.gangWeaponId) {
            properties.push('gangWeaponId');
        }
        if (this.gangId) {
            properties.push('gangId');
        }
        if (this.weapon) {
            properties.push('weapon');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}