/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { HttpParams } from '@angular/common/http';

export class GangerSkill {
    public skillId: number;
    public gangerId: string;

    public constructor(partial: Partial<GangerSkill>) {
        if (partial.skillId) {
            this.skillId = partial.skillId;
        }
        if (partial.gangerId) {
            this.gangerId = partial.gangerId;
        }
    }

    public toHttpParams(): HttpParams {
        let params = new HttpParams();
        let properties = [];
        if (this.skillId) {
            properties.push('skillId');
        }
        if (this.gangerId) {
            properties.push('gangerId');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}