/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Ganger } from './Ganger';
import { GangTerritory } from './GangTerritory';
import { HttpParams } from '@angular/common/http';

export class Gang {
    public gangId: string;
    public name: string;
    public credits: number;
    public gangHouse: string;
    public gangers: Ganger[];
    public territories: GangTerritory[];
    public gangRating: number;

    public constructor(partial: Partial<Gang>) {
        if (partial.gangId) {
            this.gangId = partial.gangId;
        }
        if (partial.name) {
            this.name = partial.name;
        }
        if (partial.credits) {
            this.credits = partial.credits;
        }
        if (partial.gangHouse) {
            this.gangHouse = partial.gangHouse;
        }
        if (partial.gangers) {
            this.gangers = partial.gangers;
        }
        if (partial.territories) {
            this.territories = partial.territories;
        }
        if (partial.gangRating) {
            this.gangRating = partial.gangRating;
        }
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //    .set('gangId', this.gangId !== undefined ? this.gangId.toString() : '')
        //    .set('name', this.name !== undefined ? this.name.toString() : '')
        //    .set('credits', this.credits !== undefined ? this.credits.toString() : '')
        //    .set('gangHouse', this.gangHouse !== undefined ? this.gangHouse.toString() : '')
        //    .set('gangers', this.gangers !== undefined ? this.gangers.toString() : '')
        //    .set('territories', this.territories !== undefined ? this.territories.toString() : '')
        //    .set('gangRating', this.gangRating !== undefined ? this.gangRating.toString() : '')
        //      ;

        let params = new HttpParams();
        let properties = [];
        if (this.gangId) {
            properties.push('gangId');
        }
        if (this.name) {
            properties.push('name');
        }
        if (this.credits) {
            properties.push('credits');
        }
        if (this.gangHouse) {
            properties.push('gangHouse');
        }
        if (this.gangers) {
            properties.push('gangers');
        }
        if (this.territories) {
            properties.push('territories');
        }
        if (this.gangRating) {
            properties.push('gangRating');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}