/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { HttpParams } from '@angular/common/http';

export class Ganger {
    public gangerId: string;
    public gangId: string;
    public name: string;
    public gangerType: string;
    public move: number;
    public weaponSkill: number;
    public ballisticSkill: number;
    public strength: number;
    public toughness: number;
    public wounds: number;
    public initiative: number;
    public attack: number;
    public leadership: number;
    public experience: number;
    public cost: number;
    public skills: number;
    public injuries: number;
    public active: boolean;
    public title: string;
    public isOneEyed: boolean;
    public isDeafened: boolean;
    public isOneHanded: boolean;
    public rightHandFingers: number;
    public leftHandFingers: number;
    public hasHorribleScars: boolean;
    public hasImpressiveScars: boolean;
    public hasHeadWound: boolean;
    public hasOldBattleWound: boolean;
    public isCaptured: boolean;
    public hasBitterEnmity: boolean;
    public hasSporeSickness: boolean;

    public constructor(partial: Partial<Ganger>) {
        if (partial.gangerId) {
            this.gangerId = partial.gangerId;
        }
        if (partial.gangId) {
            this.gangId = partial.gangId;
        }
        if (partial.name) {
            this.name = partial.name;
        }
        if (partial.gangerType) {
            this.gangerType = partial.gangerType;
        }
        if (partial.move) {
            this.move = partial.move;
        }
        if (partial.weaponSkill) {
            this.weaponSkill = partial.weaponSkill;
        }
        if (partial.ballisticSkill) {
            this.ballisticSkill = partial.ballisticSkill;
        }
        if (partial.strength) {
            this.strength = partial.strength;
        }
        if (partial.toughness) {
            this.toughness = partial.toughness;
        }
        if (partial.wounds) {
            this.wounds = partial.wounds;
        }
        if (partial.initiative) {
            this.initiative = partial.initiative;
        }
        if (partial.attack) {
            this.attack = partial.attack;
        }
        if (partial.leadership) {
            this.leadership = partial.leadership;
        }
        if (partial.experience) {
            this.experience = partial.experience;
        }
        if (partial.cost) {
            this.cost = partial.cost;
        }
        if (partial.skills) {
            this.skills = partial.skills;
        }
        if (partial.injuries) {
            this.injuries = partial.injuries;
        }
        if (partial.active) {
            this.active = partial.active;
        }
        if (partial.title) {
            this.title = partial.title;
        }
        if (partial.isOneEyed) {
            this.isOneEyed = partial.isOneEyed;
        }
        if (partial.isDeafened) {
            this.isDeafened = partial.isDeafened;
        }
        if (partial.isOneHanded) {
            this.isOneHanded = partial.isOneHanded;
        }
        if (partial.rightHandFingers) {
            this.rightHandFingers = partial.rightHandFingers;
        }
        if (partial.leftHandFingers) {
            this.leftHandFingers = partial.leftHandFingers;
        }
        if (partial.hasHorribleScars) {
            this.hasHorribleScars = partial.hasHorribleScars;
        }
        if (partial.hasImpressiveScars) {
            this.hasImpressiveScars = partial.hasImpressiveScars;
        }
        if (partial.hasHeadWound) {
            this.hasHeadWound = partial.hasHeadWound;
        }
        if (partial.hasOldBattleWound) {
            this.hasOldBattleWound = partial.hasOldBattleWound;
        }
        if (partial.isCaptured) {
            this.isCaptured = partial.isCaptured;
        }
        if (partial.hasBitterEnmity) {
            this.hasBitterEnmity = partial.hasBitterEnmity;
        }
        if (partial.hasSporeSickness) {
            this.hasSporeSickness = partial.hasSporeSickness;
        }
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //    .set('gangerId', this.gangerId !== undefined ? this.gangerId.toString() : '')
        //    .set('gangId', this.gangId !== undefined ? this.gangId.toString() : '')
        //    .set('name', this.name !== undefined ? this.name.toString() : '')
        //    .set('gangerType', this.gangerType !== undefined ? this.gangerType.toString() : '')
        //    .set('move', this.move !== undefined ? this.move.toString() : '')
        //    .set('weaponSkill', this.weaponSkill !== undefined ? this.weaponSkill.toString() : '')
        //    .set('ballisticSkill', this.ballisticSkill !== undefined ? this.ballisticSkill.toString() : '')
        //    .set('strength', this.strength !== undefined ? this.strength.toString() : '')
        //    .set('toughness', this.toughness !== undefined ? this.toughness.toString() : '')
        //    .set('wounds', this.wounds !== undefined ? this.wounds.toString() : '')
        //    .set('initiative', this.initiative !== undefined ? this.initiative.toString() : '')
        //    .set('attack', this.attack !== undefined ? this.attack.toString() : '')
        //    .set('leadership', this.leadership !== undefined ? this.leadership.toString() : '')
        //    .set('experience', this.experience !== undefined ? this.experience.toString() : '')
        //    .set('cost', this.cost !== undefined ? this.cost.toString() : '')
        //    .set('skills', this.skills !== undefined ? this.skills.toString() : '')
        //    .set('injuries', this.injuries !== undefined ? this.injuries.toString() : '')
        //    .set('active', this.active !== undefined ? this.active.toString() : '')
        //    .set('title', this.title !== undefined ? this.title.toString() : '')
        //    .set('isOneEyed', this.isOneEyed !== undefined ? this.isOneEyed.toString() : '')
        //    .set('isDeafened', this.isDeafened !== undefined ? this.isDeafened.toString() : '')
        //    .set('isOneHanded', this.isOneHanded !== undefined ? this.isOneHanded.toString() : '')
        //    .set('rightHandFingers', this.rightHandFingers !== undefined ? this.rightHandFingers.toString() : '')
        //    .set('leftHandFingers', this.leftHandFingers !== undefined ? this.leftHandFingers.toString() : '')
        //    .set('hasHorribleScars', this.hasHorribleScars !== undefined ? this.hasHorribleScars.toString() : '')
        //    .set('hasImpressiveScars', this.hasImpressiveScars !== undefined ? this.hasImpressiveScars.toString() : '')
        //    .set('hasHeadWound', this.hasHeadWound !== undefined ? this.hasHeadWound.toString() : '')
        //    .set('hasOldBattleWound', this.hasOldBattleWound !== undefined ? this.hasOldBattleWound.toString() : '')
        //    .set('isCaptured', this.isCaptured !== undefined ? this.isCaptured.toString() : '')
        //    .set('hasBitterEnmity', this.hasBitterEnmity !== undefined ? this.hasBitterEnmity.toString() : '')
        //    .set('hasSporeSickness', this.hasSporeSickness !== undefined ? this.hasSporeSickness.toString() : '')
        //      ;

        let params = new HttpParams();
        let properties = [];
        if (this.gangerId) {
            properties.push('gangerId');
        }
        if (this.gangId) {
            properties.push('gangId');
        }
        if (this.name) {
            properties.push('name');
        }
        if (this.gangerType) {
            properties.push('gangerType');
        }
        if (this.move) {
            properties.push('move');
        }
        if (this.weaponSkill) {
            properties.push('weaponSkill');
        }
        if (this.ballisticSkill) {
            properties.push('ballisticSkill');
        }
        if (this.strength) {
            properties.push('strength');
        }
        if (this.toughness) {
            properties.push('toughness');
        }
        if (this.wounds) {
            properties.push('wounds');
        }
        if (this.initiative) {
            properties.push('initiative');
        }
        if (this.attack) {
            properties.push('attack');
        }
        if (this.leadership) {
            properties.push('leadership');
        }
        if (this.experience) {
            properties.push('experience');
        }
        if (this.cost) {
            properties.push('cost');
        }
        if (this.skills) {
            properties.push('skills');
        }
        if (this.injuries) {
            properties.push('injuries');
        }
        if (this.active) {
            properties.push('active');
        }
        if (this.title) {
            properties.push('title');
        }
        if (this.isOneEyed) {
            properties.push('isOneEyed');
        }
        if (this.isDeafened) {
            properties.push('isDeafened');
        }
        if (this.isOneHanded) {
            properties.push('isOneHanded');
        }
        if (this.rightHandFingers) {
            properties.push('rightHandFingers');
        }
        if (this.leftHandFingers) {
            properties.push('leftHandFingers');
        }
        if (this.hasHorribleScars) {
            properties.push('hasHorribleScars');
        }
        if (this.hasImpressiveScars) {
            properties.push('hasImpressiveScars');
        }
        if (this.hasHeadWound) {
            properties.push('hasHeadWound');
        }
        if (this.hasOldBattleWound) {
            properties.push('hasOldBattleWound');
        }
        if (this.isCaptured) {
            properties.push('isCaptured');
        }
        if (this.hasBitterEnmity) {
            properties.push('hasBitterEnmity');
        }
        if (this.hasSporeSickness) {
            properties.push('hasSporeSickness');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}