/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { HttpParams } from '@angular/common/http';

export class GangerLevelUpReport {
    public gangerName: string;
    public description: string;
    public newSkillFromCategory: any;

    public constructor(partial: Partial<GangerLevelUpReport>) {
        if (partial.gangerName) {
            this.gangerName = partial.gangerName;
        }
        if (partial.description) {
            this.description = partial.description;
        }
        if (partial.newSkillFromCategory) {
            this.newSkillFromCategory = partial.newSkillFromCategory;
        }
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //    .set('gangerName', this.gangerName !== undefined ? this.gangerName.toString() : '')
        //    .set('description', this.description !== undefined ? this.description.toString() : '')
        //    .set('newSkillFromCategory', this.newSkillFromCategory !== undefined ? this.newSkillFromCategory.toString() : '')
        //      ;

        let params = new HttpParams();
        let properties = [];
        if (this.gangerName) {
            properties.push('gangerName');
        }
        if (this.description) {
            properties.push('description');
        }
        if (this.newSkillFromCategory) {
            properties.push('newSkillFromCategory');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}