/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { GangerSkillUpRequest } from './GangerSkillUpRequest';
import { HttpParams } from '@angular/common/http';

export class GangSkillUpRequest {
    public gangerSkillUpRequests: GangerSkillUpRequest[];

    public constructor(partial: Partial<GangSkillUpRequest>) {
        if (partial.gangerSkillUpRequests) {
            this.gangerSkillUpRequests = partial.gangerSkillUpRequests;
        }
    }

    public toHttpParams(): HttpParams {
        let params = new HttpParams();
        let properties = [];
        if (this.gangerSkillUpRequests) {
            properties.push('gangerSkillUpRequests');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}