/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { TerritoryIncomeReport } from './TerritoryIncomeReport';
import { HttpParams } from '@angular/common/http';

export class IncomeReport {
    public gross: TerritoryIncomeReport[];
    public giantKillerBonus: number;
    public income: number;

    public constructor(partial: Partial<IncomeReport>) {
        if (partial.gross) {
            this.gross = partial.gross;
        }
        if (partial.giantKillerBonus) {
            this.giantKillerBonus = partial.giantKillerBonus;
        }
        if (partial.income) {
            this.income = partial.income;
        }
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //    .set('gross', this.gross !== undefined ? this.gross.toString() : '')
        //    .set('giantKillerBonus', this.giantKillerBonus !== undefined ? this.giantKillerBonus.toString() : '')
        //    .set('income', this.income !== undefined ? this.income.toString() : '')
        //      ;

        let params = new HttpParams();
        let properties = [];
        if (this.gross) {
            properties.push('gross');
        }
        if (this.giantKillerBonus) {
            properties.push('giantKillerBonus');
        }
        if (this.income) {
            properties.push('income');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}