/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { GangerInjuryReport } from './GangerInjuryReport';
import { HttpParams } from '@angular/common/http';

export class InjuryReport {
    public injuries: GangerInjuryReport[];

    public constructor(partial: Partial<InjuryReport>) {
        if (partial.injuries) {
            this.injuries = partial.injuries;
        }
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //    .set('injuries', this.injuries !== undefined ? this.injuries.toString() : '')
        //      ;

        let params = new HttpParams();
        let properties = [];
        if (this.injuries) {
            properties.push('injuries');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}