/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { HttpParams } from '@angular/common/http';

export class Injury {
    public injuryEnum: string;
    public name: string;
    public description: string;
    public injuryEffect: any;

    public constructor(partial: Partial<Injury>) {
        if (partial.injuryEnum) {
            this.injuryEnum = partial.injuryEnum;
        }
        if (partial.name) {
            this.name = partial.name;
        }
        if (partial.description) {
            this.description = partial.description;
        }
        if (partial.injuryEffect) {
            this.injuryEffect = partial.injuryEffect;
        }
    }

    public toHttpParams(): HttpParams {
        let params = new HttpParams();
        let properties = [];
        if (this.injuryEnum) {
            properties.push('injuryEnum');
        }
        if (this.name) {
            properties.push('name');
        }
        if (this.description) {
            properties.push('description');
        }
        if (this.injuryEffect) {
            properties.push('injuryEffect');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}