/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

export enum injuryEnum {
    DEAD = 1,
    MULTIPLE_INJURIES,
    CHEST_WOUND,
    LEG_WOUND,
    ARM_WOUND,
    HEAD_WOUND,
    BLINDED_IN_ONE_EYE,
    PARTIALLY_DEAFENED,
    SHELL_SHOCK,
    HAND_INJURY,
    OLD_BATTLE_WOUND,
    FULL_RECOVERY,
    BITTER_ENMITY,
    CAPTURED,
    HORRIBLE_SCARS,
    IMPRESSIVE_SCARS,
    SURVIVES_AGAINST_THE_ODDS,
    SPORE_SICKNESS,
}