/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { HttpParams } from '@angular/common/http';

export class Login {
    public userId: number;
    public email: string;
    public password: string;
    public userGuid: string;

    public constructor(partial: Partial<Login>) {
        if (partial.userId) {
            this.userId = partial.userId;
        }
        if (partial.email) {
            this.email = partial.email;
        }
        if (partial.password) {
            this.password = partial.password;
        }
        if (partial.userGuid) {
            this.userGuid = partial.userGuid;
        }
    }

    public toHttpParams(): HttpParams {
        let params = new HttpParams();
        let properties = [];
        if (this.userId) {
            properties.push('userId');
        }
        if (this.email) {
            properties.push('email');
        }
        if (this.password) {
            properties.push('password');
        }
        if (this.userGuid) {
            properties.push('userGuid');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}