/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { HttpParams } from '@angular/common/http';

export class PreGameReport {

    public constructor(partial: Partial<PreGameReport>) {
    }

    public toHttpParams(): HttpParams {
        //return new HttpParams()
        //      ;

        let params = new HttpParams();
        let properties = [];

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}