/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

export enum skillType {
    AGILITY = 1,
    COMBAT,
    STEALTH,
    MUSCLE,
    FEROCITY,
    TECHNO,
    SHOOTING,
}