/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

export enum skillCategory {
    Agility = 1,
    Combat,
    Stealth,
    Muscle,
    Ferocity,
    Techno,
    Shooting,
}