/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { HttpParams } from '@angular/common/http';

export class TerritoryIncomeReport {
    public description: string;
    public income: number;

    public constructor(partial: Partial<TerritoryIncomeReport>) {
        if (partial.description) {
            this.description = partial.description;
        }
        if (partial.income) {
            this.income = partial.income;
        }
    }

    public toHttpParams(): HttpParams {
        let params = new HttpParams();
        let properties = [];
        if (this.description) {
            properties.push('description');
        }
        if (this.income) {
            properties.push('income');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}