/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

export enum title {
    GREEN_JUVE = 1,
    JUVE,
    TOP_JUVE,
    NEW_GANGER,
    GANGER,
    GANG_CHAMPION,
    GANG_HERO,
    MIGHTY_GANGER,
}