/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

export enum title {
    GreenJuve = 1,
    Juve,
    TopJuve,
    NewGanger,
    Ganger,
    GangChampion,
    GangHero,
    MightyGanger,
}