/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Gang } from './Gang';
import { HttpParams } from '@angular/common/http';

export class User {
    public email: string;
    public userGuid: string;
    public userGangs: Gang[];

    public constructor(partial: Partial<User>) {
        if (partial.email) {
            this.email = partial.email;
        }
        if (partial.userGuid) {
            this.userGuid = partial.userGuid;
        }
        if (partial.userGangs) {
            this.userGangs = partial.userGangs;
        }
    }

    public toHttpParams(): HttpParams {
        let params = new HttpParams();
        let properties = [];
        if (this.email) {
            properties.push('email');
        }
        if (this.userGuid) {
            properties.push('userGuid');
        }
        if (this.userGangs) {
            properties.push('userGangs');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}