/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { HttpParams } from '@angular/common/http';

export class Weapon {
    public weaponId: string;
    public name: string;
    public weaponType: string;
    public weaponAvailability: string;
    public shortRange: string;
    public longRange: string;
    public hitShort: string;
    public hitLong: string;
    public strength: string;
    public damage: string;
    public saveMod: string;
    public ammoRoll: string;
    public cost: string;
    public specialRules: string;
    public effect: any;

    public constructor(partial: Partial<Weapon>) {
        if (partial.weaponId) {
            this.weaponId = partial.weaponId;
        }
        if (partial.name) {
            this.name = partial.name;
        }
        if (partial.weaponType) {
            this.weaponType = partial.weaponType;
        }
        if (partial.weaponAvailability) {
            this.weaponAvailability = partial.weaponAvailability;
        }
        if (partial.shortRange) {
            this.shortRange = partial.shortRange;
        }
        if (partial.longRange) {
            this.longRange = partial.longRange;
        }
        if (partial.hitShort) {
            this.hitShort = partial.hitShort;
        }
        if (partial.hitLong) {
            this.hitLong = partial.hitLong;
        }
        if (partial.strength) {
            this.strength = partial.strength;
        }
        if (partial.damage) {
            this.damage = partial.damage;
        }
        if (partial.saveMod) {
            this.saveMod = partial.saveMod;
        }
        if (partial.ammoRoll) {
            this.ammoRoll = partial.ammoRoll;
        }
        if (partial.cost) {
            this.cost = partial.cost;
        }
        if (partial.specialRules) {
            this.specialRules = partial.specialRules;
        }
        if (partial.effect) {
            this.effect = partial.effect;
        }
    }

    public toHttpParams(): HttpParams {
        let params = new HttpParams();
        let properties = [];
        if (this.weaponId) {
            properties.push('weaponId');
        }
        if (this.name) {
            properties.push('name');
        }
        if (this.weaponType) {
            properties.push('weaponType');
        }
        if (this.weaponAvailability) {
            properties.push('weaponAvailability');
        }
        if (this.shortRange) {
            properties.push('shortRange');
        }
        if (this.longRange) {
            properties.push('longRange');
        }
        if (this.hitShort) {
            properties.push('hitShort');
        }
        if (this.hitLong) {
            properties.push('hitLong');
        }
        if (this.strength) {
            properties.push('strength');
        }
        if (this.damage) {
            properties.push('damage');
        }
        if (this.saveMod) {
            properties.push('saveMod');
        }
        if (this.ammoRoll) {
            properties.push('ammoRoll');
        }
        if (this.cost) {
            properties.push('cost');
        }
        if (this.specialRules) {
            properties.push('specialRules');
        }
        if (this.effect) {
            properties.push('effect');
        }

        properties.forEach(prop => {
            params = params.set(prop, this[prop]);
        });

        return params;
    }
}