/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

export enum weaponType {
    HandToHand = 1,
    Pistols,
    Basic,
    Special,
    Heavy,
    Grenades,
    Armour,
    AmmunitionAndGunsights,
    Bionics,
    Miscellaneous,
}