/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

export enum weaponType {
    HAND_TO_HAND = 1,
    PISTOLS,
    BASIC,
    SPECIAL,
    HEAVY,
    GRENADES,
    ARMOUR,
    AMMUNITION_AND_GUNSIGHTS,
    BIONICS,
    MISCELLANEOUS,
}