import { NgRedux } from '@angular-redux/store';
import { Component, OnInit } from '@angular/core';
import { IAppState } from '../redux/IAppState';
import { Weapon } from '../../autogenerated/entities/Weapon';
import { WeaponService } from '../redux/WeaponService';

@Component({
  selector: 'app-weapons',
  templateUrl: './weapons.component.html',
  styleUrls: ['./weapons.component.css']
})
export class WeaponsComponent implements OnInit {

  public weapons: Weapon[];

  constructor(
    private _ngRedux: NgRedux<IAppState>
  ) {
    this._ngRedux.subscribe(() => {
      const state = this._ngRedux.getState();
      this.weapons = state.weapons;
    });
  }

  ngOnInit() {
    const state = this._ngRedux.getState();
    if (state.weapons) {
      this.weapons = state.weapons;
    }
  }

}
