/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import { TokenService } from './../../app/redux/TokenService';
import { FormDataHelper } from '../../app/clients/FormDataHelper';
import { Gang } from '../entities/Gang';
import { Weapon } from '../entities/Weapon';
import { GangWeapon } from '../entities/GangWeapon';

@Injectable()
export class GangsClient {

    constructor(
        private _http: HttpClient, 
        private _tokenService: TokenService,
        private _formDataHelper: FormDataHelper
    ) {}

    public GetGang(
        gangId: string,
    ): Observable<Gang> {

        return this._http.get<Gang>(
            'http://localhost:61774/api/gangs/' + gangId + ''
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public AddGang(
        gang: Gang,
    ): Observable<Gang> {
        const body = this._formDataHelper.getFormData(gang);

        return this._http.post<Gang>(
            'http://localhost:61774/api/gangs'
            , body
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public GetGangStash(
        gangId: string,
    ): Observable<Weapon[]> {

        return this._http.get<Weapon[]>(
            'http://localhost:61774/api/gangs/' + gangId + '/weapons'
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public AddGangWeapon(
        gangId: string,
        gangWeapon: GangWeapon,
    ): Observable<GangWeapon> {
        const body = this._formDataHelper.getFormData(gangWeapon);

        return this._http.post<GangWeapon>(
            'http://localhost:61774/api/gangs/' + gangId + '/weapons'
            , body
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public GetGangerWeapons(
        gangId: string,
    ): Observable<Weapon[]> {

        return this._http.get<Weapon[]>(
            'http://localhost:61774/api/gangs/' + gangId + '/weapons/gangers'
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public UpdateGang(
        gang: Gang,
    ): Observable<Gang> {
        const body = this._formDataHelper.getFormData(gang);

        return this._http.put<Gang>(
            'http://localhost:61774/api/Gangs'
            , body
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

}
