/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import { TokenService } from './../../app/redux/TokenService';
import { FormDataHelper } from '../../app/clients/FormDataHelper';
import { ClientService } from './../../app/clients/ClientService';
import { Territory } from '../entities/Territory';
import { GangTerritory } from '../entities/GangTerritory';

@Injectable()
export class TerritoriesClient {
    private _path: string;

    constructor(
        private _http: HttpClient, 
        private _tokenService: TokenService,
        private _formDataHelper: FormDataHelper,
        private _clientService: ClientService
    ) {
        this._clientService.dataObs.subscribe(res => {
            this._path = res;
        });
        this._clientService.getPath();
    }

    public GetGangTerritoryById(
        gangId: string,
    ): Observable<Territory[]> {


        return this._http.get<Territory[]>(
            this._path + '/api/territories/' + gangId + ''
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public AddGangTerritory(
        gangId: string,
        territory: Territory,
    ): Observable<GangTerritory> {

        const body = this._formDataHelper.getFormData(territory);

        return this._http.post<GangTerritory>(
            this._path + '/api/territories/' + gangId + ''
            , body
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public RemoveGangTerritory(
        gangTerritoryId: string,
    ): Observable<string> {


        return this._http.delete<string>(
            this._path + '/api/territories/' + gangTerritoryId + ''
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public GetAllTerritories(
    ): Observable<Territory[]> {


        return this._http.get<Territory[]>(
            this._path + '/api/Territories'
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

}
