/*
 * This file is autogenerated. Please see README.md for instructions on editing.
 */

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import { TokenService } from './../../app/redux/TokenService';
import { FormDataHelper } from '../../app/clients/FormDataHelper';
import { ClientService } from './../../app/clients/ClientService';
import { Weapon } from '../entities/Weapon';

@Injectable()
export class WeaponsClient {

    constructor(
        private _http: HttpClient, 
        private _tokenService: TokenService,
        private _formDataHelper: FormDataHelper,
        private _clientService: ClientService,
        private _path: string
    ) {}

    public GetWeapon(
        weaponId: number,
    ): Observable<Weapon> {

        this.ensurePathExists();


        return this._http.get<Weapon>(
            this._path + '/api/weapons/' + weaponId + ''
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }

    public GetAllWeapons(
    ): Observable<Weapon[]> {

        this.ensurePathExists();


        return this._http.get<Weapon[]>(
            this._path + '/api/Weapons'
            , {
                headers: new HttpHeaders({
                    'Authorization': 'Bearer ' + this._tokenService.token,
                    'Content-Type': 'application/x-www-form-urlencoded'
                })
            }
        );
    }


    private ensurePathExists() {
        if (!this._path) {
            this._path = this._clientService.getPath();
        }
    }
}
