// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Hivemind.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Experience")]
    public partial class ExperienceFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Experience.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Experience", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get the underdog bonus after winning with a small difference")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void GetTheUnderdogBonusAfterWinningWithASmallDifference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get the underdog bonus after winning with a small difference", new string[] {
                        "mytag"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("my gang has a rating of 1000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "OpponentGangRating",
                        "HasWon"});
            table1.AddRow(new string[] {
                        "1050",
                        "true"});
#line 6
 testRunner.And("a battle report as follows:", ((string)(null)), table1, "And ");
#line 9
 testRunner.When("I calculate the underdog bonus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then("the experience result should be 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get the underdog bonus after losing with a large difference")]
        public virtual void GetTheUnderdogBonusAfterLosingWithALargeDifference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get the underdog bonus after losing with a large difference", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("my gang has a rating of 1000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "OpponentGangRating",
                        "HasWon"});
            table2.AddRow(new string[] {
                        "2501",
                        "false"});
#line 14
 testRunner.And("a battle report as follows:", ((string)(null)), table2, "And ");
#line 17
 testRunner.When("I calculate the underdog bonus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("the experience result should be 9", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calculate the wounding hit bonus")]
        public virtual void CalculateTheWoundingHitBonus()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate the wounding hit bonus", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("a ganger has downed 3 opponents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.When("I calculate the wounding hit bonus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then("the experience result should be 15", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get leader\'s bonus for winning a gang fight")]
        public virtual void GetLeadersBonusForWinningAGangFight()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get leader\'s bonus for winning a gang fight", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "GangerType",
                        "Experience"});
            table3.AddRow(new string[] {
                        "Leader",
                        "LEADER",
                        "61"});
#line 26
 testRunner.Given("a ganger with experience as follows:", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "HasWon",
                        "GameType"});
            table4.AddRow(new string[] {
                        "true",
                        "GANG_FIGHT"});
#line 29
 testRunner.And("a battle report as follows:", ((string)(null)), table4, "And ");
#line 32
 testRunner.When("I calculate the leader\'s bonus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.Then("the experience result should be 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get leader\'s bonus for winning the defense of a rescue mission")]
        public virtual void GetLeadersBonusForWinningTheDefenseOfARescueMission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get leader\'s bonus for winning the defense of a rescue mission", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "GangerType",
                        "Experience"});
            table5.AddRow(new string[] {
                        "Leader",
                        "LEADER",
                        "61"});
#line 36
 testRunner.Given("a ganger with experience as follows:", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "HasWon",
                        "IsAttacker",
                        "GameType"});
            table6.AddRow(new string[] {
                        "true",
                        "false",
                        "RESCUE_MISSION"});
#line 39
 testRunner.And("a battle report as follows:", ((string)(null)), table6, "And ");
#line 42
 testRunner.When("I calculate the leader\'s bonus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.Then("the experience result should be 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get the appropriate number of advance rolls for a Juve.")]
        public virtual void GetTheAppropriateNumberOfAdvanceRollsForAJuve_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get the appropriate number of advance rolls for a Juve.", ((string[])(null)));
#line 45
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "GangerType",
                        "Experience"});
            table7.AddRow(new string[] {
                        "Juve",
                        "JUVE",
                        "0"});
#line 46
 testRunner.Given("a ganger with experience as follows:", ((string)(null)), table7, "Given ");
#line 49
 testRunner.When("the ganger gets 16 experience", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.Then("the experience result should be 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get the appropriate number of advance rolls for a Ganger")]
        public virtual void GetTheAppropriateNumberOfAdvanceRollsForAGanger()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get the appropriate number of advance rolls for a Ganger", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Type",
                        "Experience"});
            table8.AddRow(new string[] {
                        "Ganger",
                        "GANGER",
                        "40"});
#line 53
 testRunner.Given("a ganger with experience as follows:", ((string)(null)), table8, "Given ");
#line 56
 testRunner.When("the ganger gets 5 experience", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.Then("the experience result should be 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get the correct experience for collecting objectives in a rescue mission")]
        public virtual void GetTheCorrectExperienceForCollectingObjectivesInARescueMission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get the correct experience for collecting objectives in a rescue mission", ((string[])(null)));
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
 testRunner.Given("a ganger collects 3 objectives", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "HasWon",
                        "GameType"});
            table9.AddRow(new string[] {
                        "true",
                        "RESCUE_MISSION"});
#line 61
 testRunner.And("a battle report as follows:", ((string)(null)), table9, "And ");
#line 64
 testRunner.When("I calculate the objective bonus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.Then("the experience result should be 15", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get the correct experience for collecting objectives in a gang fight")]
        public virtual void GetTheCorrectExperienceForCollectingObjectivesInAGangFight()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get the correct experience for collecting objectives in a gang fight", ((string[])(null)));
#line 67
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "GameType"});
            table10.AddRow(new string[] {
                        "GANG_FIGHT"});
#line 68
 testRunner.Given("a battle report as follows:", ((string)(null)), table10, "Given ");
#line 71
 testRunner.And("a ganger collects 0 objectives", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.When("I calculate the objective bonus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.Then("the experience result should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get bonus for winning a hit and run scenario")]
        public virtual void GetBonusForWinningAHitAndRunScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get bonus for winning a hit and run scenario", ((string[])(null)));
#line 75
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "HasWon",
                        "GameType"});
            table11.AddRow(new string[] {
                        "true",
                        "HIT_AND_RUN"});
#line 76
 testRunner.Given("a battle report as follows:", ((string)(null)), table11, "Given ");
#line 79
 testRunner.When("I calculate the winning bonus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.Then("the experience result should be 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
