using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Hivemind.Enums
{
    public enum WeaponEnum
    {
        MASSIVE_AXE = 1,
        CLUB,
        CHAINS,
        CHAINSWORD,
        SWORD,
        POWER_SWORD,
        POWER_AXE,
        POWER_FIST,
        POWER_MAUL,
        AUTOPISTOL,
        BOLT_PISTOL,
        LASPISTOL,
        NEEDLE_PISTOL,
        PLASMA_PISTOL,
        STUB_GUN,
        WEB_PISTOL,
        HAND_FLAMER,
        AUTOGUN,
        BOLTGUN,
        LASGUN,
        SHOTGUN_SOLID_SLUG,
        SHOTGUN_SCATTER_SHOT,
        SHOTGUN_MAN_STOPPER,
        SHOTGUN_HOT_SHOT,
        SHOTGUN_BOLT,
        FLAMER,
        GRENADE_LAUNCHER,
        MELTA_GUN,
        NEEDLE_RIFLE,
        PLASMA_GUN_LOW_ENERGY,
        PLASMA_GUN_HIGH_ENERGY,
        AUTOCANNON,
        HEAVY_BOLTER,
        HEAVY_PLASMA_GUN,
        HEAVY_STUBBER,
        LASCANNON,
        MISSILE_LAUNCHER_KRAK_MISSILE,
        MISSILE_LAUNCHER_FRAG_MISSILE,
        KRAK_GRENADE,
        FRAG_GRENADE,
        MELTA_BOMB, 
        GAS_GRENADE,
        PLASMA_GRENADE,
        PHOTON_FLASH_FLARE,
        SMOKE_GRENADE,
        CARAPACE_ARMOR,
        FLAK_ARMOR,
        MESH_ARMOR,
        HOTSHOT_LASER_POWER_PACK,
        INFRA_RED_SIGHT,
        MONO_SIGHT,
        RED_DOT_LASER_SIGHT,
        TELESCOPIC_SIGHT,
        BIONIC_EYE,
        BIONIC_LEG,
        BIONIC_ARM,
        AUTO_REPAIRER,
        BIO_BOOSTER,
        BIO_SCANNER,
        BLINDSNAKE_POUCH,
        CLIP_HARNESS,
        CONCEALED_BLADE,
        FILTER_PLUGS,
        GRAV_CHUTE,
        GRAPNEL,
        INFRA_RED_GOGGLES,
        ISOTROPIC_FUEL_ROD,
        LOBO_CHIP,
        MUNG_VASE,
        MEDI_PACK,
        ONE_IN_A_MILLION_WEAPON,
        PHOTO_CONTACTS,
        PHOTO_VISOR,
        SILENCER,
        SKULL_CHIP,
        RATSKIN_MAP,
        RESPIRATOR,
        SCREAMERS,
        STUMMERS,
        WEAPON_RELOADS
    }
}
