import { Injectable } from '@angular/core';
import { NgRedux } from '@angular-redux/store';
import { GameClient } from './../../autogenerated/clients/GameClient';
import { IAppState } from './IAppState';

@Injectable()
export class GameService {

    constructor(
        private _ngRedux: NgRedux<IAppState>,
        private _gameClient: GameClient) {
    }

    public processGame(battleReport) {
        this._gameClient.ProcessPostGame(battleReport).subscribe(report => {
            // do something here
        });
    }
}
