import { GangerSkillUpRequest } from './../../autogenerated/entities/GangerSkillUpRequest';
import { BattleReport } from './../../autogenerated/entities/BattleReport';
import { Gang } from './../../autogenerated/entities/Gang';
import { GangsClient } from './../../autogenerated/clients/GangsClient';
import { FINISH_GAME, POST_GAME } from './GangState';
import { Injectable } from '@angular/core';
import { NgRedux } from '@angular-redux/store';
import { GameClient } from './../../autogenerated/clients/GameClient';
import { IAppState } from './IAppState';
import { GangSkillUpRequest } from '../../autogenerated/entities/GangSkillUpRequest';

@Injectable()
export class GameService {

    constructor(
        private _ngRedux: NgRedux<IAppState>,
        private _gameClient: GameClient,
        private _gangClient: GangsClient) {
    }

    public processGame(battleReport: BattleReport) {
        this._gameClient.ProcessPostGame(battleReport).subscribe(report => {
            this._ngRedux.dispatch({
                type: POST_GAME,
                payload: report
            });
        });
    }

    public learnSkills(gangId: string, skillUpRequest: GangSkillUpRequest) {
        this._gameClient.LearnSkills(skillUpRequest).subscribe(response => {

        });
        this._gangClient.GetGang(gangId);
    }
}
