import { Ganger } from './../../autogenerated/entities/Ganger';
import { GangersClient } from './../../autogenerated/clients/GangersClient';
import { IAppState } from './IAppState';
import { NgRedux } from '@angular-redux/store';
import { Injectable } from '@angular/core';
import { ADD_GANGER } from 'app/redux/GangState';
import { GangService } from 'app/redux/GangService';

@Injectable()
export class GangerService {

    constructor(
        private _ngRedux: NgRedux<IAppState>,
        private _gangersClient: GangersClient,
        private _gangService: GangService
    ) {}

    public addGanger(ganger: Ganger) {
        this._gangersClient.AddGanger(ganger).subscribe((addedGanger) => {
            this._ngRedux.dispatch({
                type: ADD_GANGER,
                payload: addedGanger
            });

            this._gangService.getGang(addedGanger.gangId);
            
        }, err => {
        });
    }
}