import { BattleReport } from './../../autogenerated/entities/BattleReport';
import { User } from './../../autogenerated/entities/User';
import { Gang } from './../../autogenerated/entities/Gang';
import { Weapon } from '../../autogenerated/entities/Weapon';
import { PostGameReport } from '../../autogenerated/entities/PostGameReport';

export interface IAppState {
    user: User;
    gang: Gang;
    token: string;
    weapons: Weapon[];
    inGame: boolean;
    battleReport: BattleReport;
    postGameReport: PostGameReport;
}
