import { User } from './../../autogenerated/entities/User';
import { Gang } from './../../autogenerated/entities/Gang';

export interface IAppState {
    user: User;
    gang: Gang;
    token: string;
}
