import { SET_USER } from './GangState';
import { UsersClient } from 'autogenerated/clients/UsersClient';
import { NgRedux } from '@angular-redux/store';
import { IAppState } from './IAppState';
import { Injectable } from '@angular/core';
import { User } from 'autogenerated/entities/User';
import { GangService } from 'app/redux/GangService';

@Injectable()
export class UserService {

  constructor(
    private _ngRedux: NgRedux<IAppState>,
    private _usersClient: UsersClient,
    private _gangService: GangService
  ) { }

  public getUser() {
    this._usersClient.GetUser().subscribe((user: User) => {
      const gangs = user.userGangIds as string[];

      if (gangs.length > 0) {
        this._gangService.getGang(gangs[0]);
      } else {
        // add new gang
      }

      this._ngRedux.dispatch({
        type: SET_USER,
        payload: user
      });
      
    }, err => {
      console.log(err);
    });
  }
}
