import { LoginModalComponent } from './login-modal/login-modal.component';
import { UserService } from './redux/UserService';
import { LoginResponse } from './clients/LoginResponse';
import { TokenService } from './redux/TokenService';
import { Gang } from './../autogenerated/entities/Gang';
import { GangService } from './redux/GangService';
import { Component, ViewChild } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { UsersClient } from 'autogenerated/clients/UsersClient';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { LoginClient } from 'app/clients/LoginClient';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {

  public title = 'Hivemind NG';
  public showSignUpDialog = false;
  public gang: Gang;
  @ViewChild('loginModal') loginModal: LoginModalComponent;
  private _loginUrl = 'http://localhost:61774/api/login';ssss

  constructor(
    private _tokenService: TokenService,
    private _userService: UserService,
    private _loginClient: LoginClient
    ) {
  }

  public showLoginModalDialog() {
    this.loginModal.display();
  }
}
