import { TerritoriesComponent } from './territories/territories.component';
import { GangersClient } from './../autogenerated/clients/GangersClient';
import { GangersComponent } from './gangers/gangers.component';
import { GangComponent } from './gang/gang.component';
import { GangsClient } from './../autogenerated/clients/GangsClient';
import { GangService } from './redux/GangService';
import { reduce } from './redux/GangState';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

import { NgReduxModule, NgRedux } from '@angular-redux/store';
import { IAppState } from './redux/IAppState';
import { Store, createStore } from 'redux';
import { HttpClientModule } from '@angular/common/http';
import { RouterModule, Routes } from '@angular/router';
import { WeaponsComponent } from './weapons/weapons.component';
import { StoreComponent } from './store/store.component';
import { StatisticsComponent } from './statistics/statistics.component';

const initialState: IAppState = {
  gang: null
};

export const createAppStore = () => {
  return createStore<IAppState>(reduce, initialState);
};

const routes: Routes = [
  { path: 'gang', component: GangComponent },
  { path: 'gangers', component: GangersComponent },
  { path: 'weapons', component: WeaponsComponent },
  { path: 'territories', component: TerritoriesComponent },
  { path: 'statistics', component: StatisticsComponent },
  { path: 'store', component: StoreComponent }
];

@NgModule({
  declarations: [
    AppComponent,
    GangComponent,
    GangersComponent,
    TerritoriesComponent,
    WeaponsComponent,
    StoreComponent,
    StatisticsComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    RouterModule.forRoot(routes)
  ],
  providers: [
    { provide: NgRedux, useFactory: createAppStore },
    GangService,
    GangsClient,
    GangersClient
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(ngRedux: NgRedux<IAppState>) {
  }
}
