//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hivemind {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hivemind.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter has smashed one arm. Although he recovers from his injury his strength is permanently reduced as a result. The fighter’s Strength characteristic is reduced by -1 when using that arm. Randomly determine which arm has been hit. Bear in mind that some hand-to-hand weapons use the fighter’s own Strength, eg swords..
        /// </summary>
        internal static string lbl_injury_arm_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_arm_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm Wound.
        /// </summary>
        internal static string lbl_injury_arm_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_arm_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although he makes a full physical recovery, the fighter has been psychologically scarred by his experiences. He develops a bitter enmity for the gang that was responsible for his injury. From now on, the fighter hates the following (roll a D6).
        ///1-2 The individual enemy who inflicted the injury (if unknown, the gang leader).
        ///3-4 The leader of the gang who inflicted the injury.
        ///5 The entire gang responsible for his injury.
        ///6 All gangs from the same House as the gang that inflicted his injury. If the same  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_injury_bitter_enmity_description {
            get {
                return ResourceManager.GetString("lbl_injury_bitter_enmity_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitter Enmity.
        /// </summary>
        internal static string lbl_injury_bitter_enmity_name {
            get {
                return ResourceManager.GetString("lbl_injury_bitter_enmity_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter survives but loses the sight of one eye. Randomly determine which eye. A character with only one eye has his Ballistic Skill reduced by -1. If the fighter is subsequently blinded in his remaining good eye then he must retire from the gang..
        /// </summary>
        internal static string lbl_injury_blinded_description {
            get {
                return ResourceManager.GetString("lbl_injury_blinded_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinded in One Eye.
        /// </summary>
        internal static string lbl_injury_blinded_name {
            get {
                return ResourceManager.GetString("lbl_injury_blinded_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter is captured. Captives may be exchanged, ransomed back or sold into slavery. If both gangs hold captives then they must be exchanged on a one-for-one basis, starting with models of the highest value. Any remaining captives must be ransomed back to their own gang if the player is willing to pay the captor’s asking price. There is no fixed value for ransom – it is a matter for the players to decide for themselves. Finally, fighters who are neither exchanged or ransomed may be sold to the Guilders a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_injury_captured_description {
            get {
                return ResourceManager.GetString("lbl_injury_captured_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured.
        /// </summary>
        internal static string lbl_injury_captured_name {
            get {
                return ResourceManager.GetString("lbl_injury_captured_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter has been badly wounded in the chest. He recovers but is weakened by the injury and his Toughness characteristic is reduced by -1..
        /// </summary>
        internal static string lbl_injury_chest_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_chest_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest Wound.
        /// </summary>
        internal static string lbl_injury_chest_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_chest_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter is killed in action and his body abandoned to the mutant rats of the Underhive. All the weapons and equipment carried by the fighter are lost..
        /// </summary>
        internal static string lbl_injury_dead_description {
            get {
                return ResourceManager.GetString("lbl_injury_dead_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        internal static string lbl_injury_dead_name {
            get {
                return ResourceManager.GetString("lbl_injury_dead_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter survives but is partially deafened as a result of his injuries. An individual suffers no penalty if he is partially deafened, but if he is deafened for a second time he suffers -1 from his Leadership characteristic..
        /// </summary>
        internal static string lbl_injury_deafened_description {
            get {
                return ResourceManager.GetString("lbl_injury_deafened_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially Deafened.
        /// </summary>
        internal static string lbl_injury_deafened_name {
            get {
                return ResourceManager.GetString("lbl_injury_deafened_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter has been knocked unconscious or suffers a mildly incapacitating wound from which he makes a full recovery..
        /// </summary>
        internal static string lbl_injury_full_recovery_description {
            get {
                return ResourceManager.GetString("lbl_injury_full_recovery_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Recovery.
        /// </summary>
        internal static string lbl_injury_full_recovery_name {
            get {
                return ResourceManager.GetString("lbl_injury_full_recovery_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wounds to a hand result in the loss of D3 fingers. Randomly determine which hand is affected. The fighter’s Weapon Skill is reduced by -1. If a fighter loses all five fingers on a hand then he may no longer use that hand: he may not carry anything in it, and is unable to use weapons that require two hands..
        /// </summary>
        internal static string lbl_injury_hand_injury_description {
            get {
                return ResourceManager.GetString("lbl_injury_hand_injury_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Injury.
        /// </summary>
        internal static string lbl_injury_hand_injury_name {
            get {
                return ResourceManager.GetString("lbl_injury_hand_injury_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A serious head injury leaves the fighter somewhat unhinged. At the start of each game roll a D6 to determine how he is affected. On a 1-3 the fighter is dazed and confused – he is affected by the rules for stupidity. On a roll of 4-6 the fighter is enraged and uncontrollable – he is affected by the rules for frenzy..
        /// </summary>
        internal static string lbl_injury_head_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_head_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Wound.
        /// </summary>
        internal static string lbl_injury_head_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_head_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter recovers from his injuries but is left horribly disfigured. His scarred and distorted features inspire fear as described in the Advanced Rules section of the rulebook..
        /// </summary>
        internal static string lbl_injury_horrible_scars_description {
            get {
                return ResourceManager.GetString("lbl_injury_horrible_scars_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horrible Scars.
        /// </summary>
        internal static string lbl_injury_horrible_scars_name {
            get {
                return ResourceManager.GetString("lbl_injury_horrible_scars_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter recovers and is left with impressive scars as testament to his bravery. Add +1 to the fighter’s Leadership characteristic. This bonus applies only once, further impressive scars have no additional effect..
        /// </summary>
        internal static string lbl_injury_impressive_scars_description {
            get {
                return ResourceManager.GetString("lbl_injury_impressive_scars_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressive Scars.
        /// </summary>
        internal static string lbl_injury_impressive_scars_name {
            get {
                return ResourceManager.GetString("lbl_injury_impressive_scars_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter has smashed a leg. He recovers from his injuries but he can no longer move quickly. The fighter’s Movement characteristic is reduced by -1. Randomly determine which leg has been hurt..
        /// </summary>
        internal static string lbl_injury_leg_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_leg_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg Wound.
        /// </summary>
        internal static string lbl_injury_leg_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_leg_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter is not dead but has suffered many serious wounds. Roll a further D6 times on this chart.  Re-roll any ‘Dead’ and ‘Full Recovery’ results.
        /// </summary>
        internal static string lbl_injury_multiple_injuries_description {
            get {
                return ResourceManager.GetString("lbl_injury_multiple_injuries_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Injuries.
        /// </summary>
        internal static string lbl_injury_multiple_injuries_name {
            get {
                return ResourceManager.GetString("lbl_injury_multiple_injuries_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter recovers but his old wound sometimes affects his health. Roll a D6 before each game. On the roll of a 1 the fighter’s old wound is playing up and he is unable to take part in the forthcoming battle..
        /// </summary>
        internal static string lbl_injury_old_battle_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_old_battle_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Battle Wound.
        /// </summary>
        internal static string lbl_injury_old_battle_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_old_battle_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter survives but is extremely nervous and jumpy as a result of the traumatic injuries he has suffered. His Initiative characteristic is reduced by -1..
        /// </summary>
        internal static string lbl_injury_shell_shock_description {
            get {
                return ResourceManager.GetString("lbl_injury_shell_shock_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Shock.
        /// </summary>
        internal static string lbl_injury_shell_shock_name {
            get {
                return ResourceManager.GetString("lbl_injury_shell_shock_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a fungal disease in which plump and colourful fungi sprout from all over the victim’s body. Spore Sickness is not lethal and recovery is automatic, but the ganger will not be able to take part in future battles until he recovers by rolling a 4, 5 or 6 at the start of a game. Once recovered he may fight as normal..
        /// </summary>
        internal static string lbl_injury_spore_sickness_description {
            get {
                return ResourceManager.GetString("lbl_injury_spore_sickness_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spore Sickness.
        /// </summary>
        internal static string lbl_injury_spore_sickness_name {
            get {
                return ResourceManager.GetString("lbl_injury_spore_sickness_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survives Against the Odds.
        /// </summary>
        internal static string lbl_injury_survives_against_the_odds_name {
            get {
                return ResourceManager.GetString("lbl_injury_survives_against_the_odds_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter regains consciousness alone in the darkness, given up for dead by his companions and overlooked by his enemies. Despite his injuries he makes his way back home. He recovers fully and his uncanny survival earns him an additional D6 Experience points..
        /// </summary>
        internal static string lbl_injury_survives_against_the_odss_description {
            get {
                return ResourceManager.GetString("lbl_injury_survives_against_the_odss_description", resourceCulture);
            }
        }
    }
}
