//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hivemind {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hivemind.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As user.
        /// </summary>
        internal static string lbl_as_user {
            get {
                return ResourceManager.GetString("lbl_as_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As user +1.
        /// </summary>
        internal static string lbl_as_user_plus_1 {
            get {
                return ResourceManager.GetString("lbl_as_user_plus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As user +2.
        /// </summary>
        internal static string lbl_as_user_plus_2 {
            get {
                return ResourceManager.GetString("lbl_as_user_plus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string lbl_auto {
            get {
                return ResourceManager.GetString("lbl_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast.
        /// </summary>
        internal static string lbl_blast {
            get {
                return ResourceManager.GetString("lbl_blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string lbl_CC {
            get {
                return ResourceManager.GetString("lbl_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string lbl_choose {
            get {
                return ResourceManager.GetString("lbl_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D6.
        /// </summary>
        internal static string lbl_dice_2d6 {
            get {
                return ResourceManager.GetString("lbl_dice_2d6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D6*10.
        /// </summary>
        internal static string lbl_dice_2d6x10 {
            get {
                return ResourceManager.GetString("lbl_dice_2d6x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D6*10.
        /// </summary>
        internal static string lbl_dice_d6x10 {
            get {
                return ResourceManager.GetString("lbl_dice_d6x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Weapon base cost.
        /// </summary>
        internal static string lbl_half_weapon_base_cost {
            get {
                return ResourceManager.GetString("lbl_half_weapon_base_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter has smashed one arm. Although he recovers from his injury his strength is permanently reduced as a result. The fighter’s Strength characteristic is reduced by -1 when using that arm. Randomly determine which arm has been hit. Bear in mind that some hand-to-hand weapons use the fighter’s own Strength, eg swords..
        /// </summary>
        internal static string lbl_injury_arm_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_arm_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm Wound.
        /// </summary>
        internal static string lbl_injury_arm_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_arm_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although he makes a full physical recovery, the fighter has been psychologically scarred by his experiences. He develops a bitter enmity for the gang that was responsible for his injury. From now on, the fighter hates the following (roll a D6).
        ///1-2 The individual enemy who inflicted the injury (if unknown, the gang leader).
        ///3-4 The leader of the gang who inflicted the injury.
        ///5 The entire gang responsible for his injury.
        ///6 All gangs from the same House as the gang that inflicted his injury. If the same  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_injury_bitter_enmity_description {
            get {
                return ResourceManager.GetString("lbl_injury_bitter_enmity_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitter Enmity.
        /// </summary>
        internal static string lbl_injury_bitter_enmity_name {
            get {
                return ResourceManager.GetString("lbl_injury_bitter_enmity_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter survives but loses the sight of one eye. Randomly determine which eye. A character with only one eye has his Ballistic Skill reduced by -1. If the fighter is subsequently blinded in his remaining good eye then he must retire from the gang..
        /// </summary>
        internal static string lbl_injury_blinded_description {
            get {
                return ResourceManager.GetString("lbl_injury_blinded_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinded in One Eye.
        /// </summary>
        internal static string lbl_injury_blinded_name {
            get {
                return ResourceManager.GetString("lbl_injury_blinded_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter is captured. Captives may be exchanged, ransomed back or sold into slavery. If both gangs hold captives then they must be exchanged on a one-for-one basis, starting with models of the highest value. Any remaining captives must be ransomed back to their own gang if the player is willing to pay the captor’s asking price. There is no fixed value for ransom – it is a matter for the players to decide for themselves. Finally, fighters who are neither exchanged or ransomed may be sold to the Guilders a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_injury_captured_description {
            get {
                return ResourceManager.GetString("lbl_injury_captured_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured.
        /// </summary>
        internal static string lbl_injury_captured_name {
            get {
                return ResourceManager.GetString("lbl_injury_captured_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter has been badly wounded in the chest. He recovers but is weakened by the injury and his Toughness characteristic is reduced by -1..
        /// </summary>
        internal static string lbl_injury_chest_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_chest_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest Wound.
        /// </summary>
        internal static string lbl_injury_chest_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_chest_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter is killed in action and his body abandoned to the mutant rats of the Underhive. All the weapons and equipment carried by the fighter are lost..
        /// </summary>
        internal static string lbl_injury_dead_description {
            get {
                return ResourceManager.GetString("lbl_injury_dead_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        internal static string lbl_injury_dead_name {
            get {
                return ResourceManager.GetString("lbl_injury_dead_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter survives but is partially deafened as a result of his injuries. An individual suffers no penalty if he is partially deafened, but if he is deafened for a second time he suffers -1 from his Leadership characteristic..
        /// </summary>
        internal static string lbl_injury_deafened_description {
            get {
                return ResourceManager.GetString("lbl_injury_deafened_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially Deafened.
        /// </summary>
        internal static string lbl_injury_deafened_name {
            get {
                return ResourceManager.GetString("lbl_injury_deafened_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter has been knocked unconscious or suffers a mildly incapacitating wound from which he makes a full recovery..
        /// </summary>
        internal static string lbl_injury_full_recovery_description {
            get {
                return ResourceManager.GetString("lbl_injury_full_recovery_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Recovery.
        /// </summary>
        internal static string lbl_injury_full_recovery_name {
            get {
                return ResourceManager.GetString("lbl_injury_full_recovery_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wounds to a hand result in the loss of D3 fingers. Randomly determine which hand is affected. The fighter’s Weapon Skill is reduced by -1. If a fighter loses all five fingers on a hand then he may no longer use that hand: he may not carry anything in it, and is unable to use weapons that require two hands..
        /// </summary>
        internal static string lbl_injury_hand_injury_description {
            get {
                return ResourceManager.GetString("lbl_injury_hand_injury_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Injury.
        /// </summary>
        internal static string lbl_injury_hand_injury_name {
            get {
                return ResourceManager.GetString("lbl_injury_hand_injury_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A serious head injury leaves the fighter somewhat unhinged. At the start of each game roll a D6 to determine how he is affected. On a 1-3 the fighter is dazed and confused – he is affected by the rules for stupidity. On a roll of 4-6 the fighter is enraged and uncontrollable – he is affected by the rules for frenzy..
        /// </summary>
        internal static string lbl_injury_head_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_head_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Wound.
        /// </summary>
        internal static string lbl_injury_head_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_head_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter recovers from his injuries but is left horribly disfigured. His scarred and distorted features inspire fear as described in the Advanced Rules section of the rulebook..
        /// </summary>
        internal static string lbl_injury_horrible_scars_description {
            get {
                return ResourceManager.GetString("lbl_injury_horrible_scars_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horrible Scars.
        /// </summary>
        internal static string lbl_injury_horrible_scars_name {
            get {
                return ResourceManager.GetString("lbl_injury_horrible_scars_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter recovers and is left with impressive scars as testament to his bravery. Add +1 to the fighter’s Leadership characteristic. This bonus applies only once, further impressive scars have no additional effect..
        /// </summary>
        internal static string lbl_injury_impressive_scars_description {
            get {
                return ResourceManager.GetString("lbl_injury_impressive_scars_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressive Scars.
        /// </summary>
        internal static string lbl_injury_impressive_scars_name {
            get {
                return ResourceManager.GetString("lbl_injury_impressive_scars_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter has smashed a leg. He recovers from his injuries but he can no longer move quickly. The fighter’s Movement characteristic is reduced by -1. Randomly determine which leg has been hurt..
        /// </summary>
        internal static string lbl_injury_leg_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_leg_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg Wound.
        /// </summary>
        internal static string lbl_injury_leg_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_leg_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter is not dead but has suffered many serious wounds. Roll a further D6 times on this chart.  Re-roll any ‘Dead’ and ‘Full Recovery’ results.
        /// </summary>
        internal static string lbl_injury_multiple_injuries_description {
            get {
                return ResourceManager.GetString("lbl_injury_multiple_injuries_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Injuries.
        /// </summary>
        internal static string lbl_injury_multiple_injuries_name {
            get {
                return ResourceManager.GetString("lbl_injury_multiple_injuries_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter recovers but his old wound sometimes affects his health. Roll a D6 before each game. On the roll of a 1 the fighter’s old wound is playing up and he is unable to take part in the forthcoming battle..
        /// </summary>
        internal static string lbl_injury_old_battle_wound_description {
            get {
                return ResourceManager.GetString("lbl_injury_old_battle_wound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Battle Wound.
        /// </summary>
        internal static string lbl_injury_old_battle_wound_name {
            get {
                return ResourceManager.GetString("lbl_injury_old_battle_wound_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter survives but is extremely nervous and jumpy as a result of the traumatic injuries he has suffered. His Initiative characteristic is reduced by -1..
        /// </summary>
        internal static string lbl_injury_shell_shock_description {
            get {
                return ResourceManager.GetString("lbl_injury_shell_shock_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Shock.
        /// </summary>
        internal static string lbl_injury_shell_shock_name {
            get {
                return ResourceManager.GetString("lbl_injury_shell_shock_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a fungal disease in which plump and colourful fungi sprout from all over the victim’s body. Spore Sickness is not lethal and recovery is automatic, but the ganger will not be able to take part in future battles until he recovers by rolling a 4, 5 or 6 at the start of a game. Once recovered he may fight as normal..
        /// </summary>
        internal static string lbl_injury_spore_sickness_description {
            get {
                return ResourceManager.GetString("lbl_injury_spore_sickness_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spore Sickness.
        /// </summary>
        internal static string lbl_injury_spore_sickness_name {
            get {
                return ResourceManager.GetString("lbl_injury_spore_sickness_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survives Against the Odds.
        /// </summary>
        internal static string lbl_injury_survives_against_the_odds_name {
            get {
                return ResourceManager.GetString("lbl_injury_survives_against_the_odds_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fighter regains consciousness alone in the darkness, given up for dead by his companions and overlooked by his enemies. Despite his injuries he makes his way back home. He recovers fully and his uncanny survival earns him an additional D6 Experience points..
        /// </summary>
        internal static string lbl_injury_survives_against_the_odss_description {
            get {
                return ResourceManager.GetString("lbl_injury_survives_against_the_odss_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string lbl_special {
            get {
                return ResourceManager.GetString("lbl_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string lbl_template {
            get {
                return ResourceManager.GetString("lbl_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gang has discovered a hidden entrance into a small unexplored dome. A ganger can collect remnants of ancient technical devices which can be sold for 2D6x10 credits.
        ///So long as your gang is careful not to sell too many items at once no one will suspect that you have discovered a new dome. No risk is incurred by collecting 2D6x10 credits. However, if you want to work the dome more intensely you can do so. A ganger can collect 3D6x10, 4D6x10, 5D6x10 or even 6D6x10 from the hoard, but if he rolls any doub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_territory_archeotech_description {
            get {
                return ResourceManager.GetString("lbl_territory_archeotech_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archeotech.
        /// </summary>
        internal static string lbl_territory_archeotech_name {
            get {
                return ResourceManager.GetString("lbl_territory_archeotech_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An extensive and highly dangerous chemical pit lies nearby. The pit is a source of constantly changing chemicals, sulphurous deposits, and all kinds of poisonous and corrosive substances. If you want to collect chemicals from the pit you gain 2D6 credits.
        ///The work is extremely hazardous. If you roll a double or a 6 when working out your credits then the ganger falls into the chem pit but manages to haul himself free. He struggles back to base horrifically scarred, his skin covered with blisters. His appear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_territory_chem_pit_description {
            get {
                return ResourceManager.GetString("lbl_territory_chem_pit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chem Pit.
        /// </summary>
        internal static string lbl_territory_chem_pit_name {
            get {
                return ResourceManager.GetString("lbl_territory_chem_pit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gang leader has inherited an old drinking hole in payment of an outstanding gambling debt. The hole earns a small sum and also provides the gang with a convenient base in the local settlement. You can visit the drinking hole to collect your share of D6x10 credits..
        /// </summary>
        internal static string lbl_territory_drinking_hole_description {
            get {
                return ResourceManager.GetString("lbl_territory_drinking_hole_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinking Hole.
        /// </summary>
        internal static string lbl_territory_drinking_hole_name {
            get {
                return ResourceManager.GetString("lbl_territory_drinking_hole_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the local medical practitioners has offered to patch up your wounded fighters at favourable rates in return for blood and tissue donations from your gangers. If a ganger wants to part with a few pints of blood or some other renewable tissue you gain D6x10 credits. The Doc will also give you D6x5 credits for the body of any of your fighters who dies in combat, providing him with a useful supply of organs and limbs for transplant..
        /// </summary>
        internal static string lbl_territory_friendly_doc_description {
            get {
                return ResourceManager.GetString("lbl_territory_friendly_doc_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Doc.
        /// </summary>
        internal static string lbl_territory_friendly_doc_name {
            get {
                return ResourceManager.GetString("lbl_territory_friendly_doc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gang runs a gambling den in an old disused hole in your settlement. Although the income from running a game is good, it is a risky business because Underhivers are notorious cheats and bad losers too. If you decide to run a gambling session you receive 2D6x10 credits. However, if you roll a double you lose that number of credits from that turn’s income instead – eg, double 4 you lose 80 credits.
        ///Note that losses are deducted from your income before making reductions for basic running costs. If a gang  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_territory_gambling_den_description {
            get {
                return ResourceManager.GetString("lbl_territory_gambling_den_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambling Den.
        /// </summary>
        internal static string lbl_territory_gambling_den_name {
            get {
                return ResourceManager.GetString("lbl_territory_gambling_den_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You befriend a group of settlers who have migrated from Hive City to the Underhive to start a new life. Possibly your gang has chanced upon the settlers lost or dying in the wastes. Maybe they are relatives or friends of one of your gang fighters who have deliberately sought him out. Thanks to your contacts and influence you are able to give the green hivers a good start, and naturally they are grateful for your assistance and only too pleased to help in the future. You may choose any type of territory from [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_territory_green_hivers_description {
            get {
                return ResourceManager.GetString("lbl_territory_green_hivers_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Hivers.
        /// </summary>
        internal static string lbl_territory_green_hivers_name {
            get {
                return ResourceManager.GetString("lbl_territory_green_hivers_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A local Guilder has offered you favourable rates in return for your business. As a result you are able to increase your income substantially. If you wish to deal with your Guilder contact you gain an extra D6x10 credits.
        ///If you recover any loot during a fight you can trade it in to your Guilder contact for an extra +5 credits income for each item..
        /// </summary>
        internal static string lbl_territory_guilder_contract_description {
            get {
                return ResourceManager.GetString("lbl_territory_guilder_contract_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilder Contract.
        /// </summary>
        internal static string lbl_territory_guilder_contract_name {
            get {
                return ResourceManager.GetString("lbl_territory_guilder_contract_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the gang fighters comes from a holestead out in the wastes. The hole produces a crop of nutritious slime which the ganger can help his family carry to the local trade post in return for D6x10 credits’ cut of the proceeds..
        /// </summary>
        internal static string lbl_territory_holestead_description {
            get {
                return ResourceManager.GetString("lbl_territory_holestead_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holestead.
        /// </summary>
        internal static string lbl_territory_holestead_name {
            get {
                return ResourceManager.GetString("lbl_territory_holestead_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a secret location in the wastes your gang has discovered a mine. The excavations yield carnotite gems or some other valuable ores or stones. Friends of the fighters are already working in return for a slice of the proceeds. You can collect D6x10 credits as your share of the profits to date.
        ///If you capture an enemy fighter then you can put him to work in your mine instead of selling him to slavers. Each captive worker adds +1 to your D6 dice roll for income from the mine..
        /// </summary>
        internal static string lbl_territory_mine_workings_description {
            get {
                return ResourceManager.GetString("lbl_territory_mine_workings_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Workings.
        /// </summary>
        internal static string lbl_territory_mine_workings_name {
            get {
                return ResourceManager.GetString("lbl_territory_mine_workings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not far from your settlement there is an outcrop of mineral wastes where a ganger can collect valuable sparstones, adonite crystals, igneous adamantorite, or one of the many other kinds of mineral gems that are formed in the Underhive. You will earn D6x10 credits by searching the outcrop for precious stones..
        /// </summary>
        internal static string lbl_territory_mineral_outcrop_description {
            get {
                return ResourceManager.GetString("lbl_territory_mineral_outcrop_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral Outcrop.
        /// </summary>
        internal static string lbl_territory_mineral_outcrop_name {
            get {
                return ResourceManager.GetString("lbl_territory_mineral_outcrop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an exposed area of ancient ruins not far from your settlement. If a ganger searches through the ruins he may find scrap pieces of archeotech, bits of old metal, or interesting old curios – enough to sell for 10 credits..
        /// </summary>
        internal static string lbl_territory_old_ruins_description {
            get {
                return ResourceManager.GetString("lbl_territory_old_ruins_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Ruins.
        /// </summary>
        internal static string lbl_territory_old_ruins_name {
            get {
                return ResourceManager.GetString("lbl_territory_old_ruins_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The families of your gang fighters own holes or workshops inside the settlement where the gang is based. These holdings help to support the gang by providing food, shelter, and a vital link with the local traders.
        ///If a ganger visits his family he collects 30 credits. In addition, whether the territory is used or not, there is a chance of a young relative leaving the settlement to join your gang. Roll a D6 after each game. On the roll of a 6 you may recruit a juve for free. You will have to pay for his weap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_territory_settlement_description {
            get {
                return ResourceManager.GetString("lbl_territory_settlement_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement.
        /// </summary>
        internal static string lbl_territory_settlement_name {
            get {
                return ResourceManager.GetString("lbl_territory_settlement_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near your settlement there is an extensive network of tunnels and crawlholes full of iron slag and other solidified chemical wastes. A ganger can work the slag by breaking it up ready to sell to the local Guilders for 15 credits..
        /// </summary>
        internal static string lbl_territory_slag_description {
            get {
                return ResourceManager.GetString("lbl_territory_slag_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slag.
        /// </summary>
        internal static string lbl_territory_slag_name {
            get {
                return ResourceManager.GetString("lbl_territory_slag_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gang has discovered a hidden cave where many kinds of rare fungi grow, such as pearl spore and iron mould. A ganger can harvest the fungi and sell it to local traders for 2D6x10 credits.
        ///If you roll double 1 when harvesting fungus the collecting ganger has contracted Spore Sickness. This is a fungal disease in which plump and colourful fungi sprout from all over the victim’s body. Spore Sickness is not lethal and recovery is automatic, but the ganger will not be able to take part in future battles unt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lbl_territory_spore_cave_description {
            get {
                return ResourceManager.GetString("lbl_territory_spore_cave_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spore Cave.
        /// </summary>
        internal static string lbl_territory_spore_cave_name {
            get {
                return ResourceManager.GetString("lbl_territory_spore_cave_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gang has found a buried entrance to a labyrinth of ancient service ducts beneath the dome floor. When the gang fights a battle it can use these ducts to position up to three fighters anywhere on the battlefield at ground level.
        ///Models are set up at the end of the player’s first turn and cannot be placed within 8&quot; of enemy models. This represents the fighters working their way behind the enemy using their secret tunnels..
        /// </summary>
        internal static string lbl_territory_tunnels_description {
            get {
                return ResourceManager.GetString("lbl_territory_tunnels_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnels.
        /// </summary>
        internal static string lbl_territory_tunnels_name {
            get {
                return ResourceManager.GetString("lbl_territory_tunnels_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gang has found a concealed entrance into a network of ancient ventilation shafts. When the gang fights a battle it can use these vents to position up to three fighters anywhere on the battlefield above ground level. Models are set up at the end of the player’s first turn and cannot be placed within 8&quot; of enemy models. This represents the fighters working their way over and around the enemy using their secret air shafts..
        /// </summary>
        internal static string lbl_territory_vents_description {
            get {
                return ResourceManager.GetString("lbl_territory_vents_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vents.
        /// </summary>
        internal static string lbl_territory_vents_name {
            get {
                return ResourceManager.GetString("lbl_territory_vents_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gang has discovered and renovated an old water still out in the wastes. The still is worked by the family or friends of one of the gangers. Guilder slave trains carry the water to local settlers making the gang a share of the proceeds amounting to D6x10 credits..
        /// </summary>
        internal static string lbl_territory_water_still_description {
            get {
                return ResourceManager.GetString("lbl_territory_water_still_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Still.
        /// </summary>
        internal static string lbl_territory_water_still_name {
            get {
                return ResourceManager.GetString("lbl_territory_water_still_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The family or friends of one of your gang fighters runs a workshop in the local settlement. You can trade in bits of scrap or other odds and ends in return for cheap repair work or cash. If you want to visit the workshop you earn D6x10 credits.
        ///In addition, thanks to your workshop’s meticulous care, you always ignore the first Ammo test during a battle. It is assumed you pass the test and no dice are rolled. Note that this only applies to the first test, not to subsequent ones..
        /// </summary>
        internal static string lbl_territory_workshop_description {
            get {
                return ResourceManager.GetString("lbl_territory_workshop_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        internal static string lbl_territory_workshop_name {
            get {
                return ResourceManager.GetString("lbl_territory_workshop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon x2.
        /// </summary>
        internal static string lbl_weapon_times_2 {
            get {
                return ResourceManager.GetString("lbl_weapon_times_2", resourceCulture);
            }
        }
    }
}
