import { GangTerritory } from './../../autogenerated/entities/GangTerritory';
import { Territory } from './../../autogenerated/entities/Territory';
import { Component, OnInit, Input } from '@angular/core';
import { IAppState } from '../redux/IAppState';
import { NgRedux } from '@angular-redux/store';

@Component({
  selector: 'territories',
  templateUrl: './territories.component.html',
  styleUrls: ['./territories.component.css']
})
export class TerritoriesComponent implements OnInit {

  public territories: Territory[];

  constructor(
    private _ngRedux: NgRedux<IAppState>
  ) {
    this._ngRedux.subscribe(() => {
      const state = this._ngRedux.getState();
      this.territories = state.gang.territories;
    });

    this.territories = new Array<Territory>();
  }

  ngOnInit() {
    const state = this._ngRedux.getState();
    if (state.gang && state.gang.territories) {
      this.territories = state.gang.territories;
    }
  }
}
