import { GangTerritory } from './../../autogenerated/entities/GangTerritory';
import { Territory } from './../../autogenerated/entities/Territory';
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'territories',
  templateUrl: './territories.component.html',
  styleUrls: ['./territories.component.css']
})
export class TerritoriesComponent implements OnInit {

  @Input() public territories: GangTerritory[];

  constructor() { }

  ngOnInit() {
  }

}
